name: Build and Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - name: Azure Login
      run: az login --service-principal -u ${{ secrets.appId }} -p ${{ secrets.password }} --tenant ${{ secrets.tenant }}
#       uses: azure/login@v1
#       with:
#         creds: ${{ secrets.AZURE_CREDENTIALS }}
    
#     - name: AKS Cluster Setup
#       run: |
#         az group create --name SNC-AKS-RG --location centralus
#         az acr create --resource-group SNC-AKS-RG --name sncacr --sku Basic
#         az aks create --resource-group SNC-AKS-RG --name SNCAKSCluster --node-count 2 --generate-ssh-keys --attach-acr SNCACR
        
    - name: Deploy Kubernetes APP
      run: kubectl apply -f $GITHUB_WORKSPACE/azure-vote-all-in-one-redis.yaml
        
    - name: Checkout
      uses: actions/checkout@v1

#     - name: Azure CLI script file
#       uses: azure/CLI@v1
#       with:
#         azcliversion: 2.30.0
#         inlineScript: |
#           chmod +x $GITHUB_WORKSPACE/sampleScript.sh
#           $GITHUB_WORKSPACE/sampleScript.sh
